services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build: .
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
