services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobdb
      TZ: Asia/Kolkata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - TZ=Asia/Kolkata

  api:
    build: .
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Kolkata

volumes:
  postgres_data:
